// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {SP1Verifier} from "../src/SP1Verifier.sol";

contract SP1VerifierTest is Test {
    SP1Verifier public verifier;

    function setUp() public {
        verifier = new SP1Verifier();
    }

    function test_Version() public view {
        assertEq(verifier.VERSION(), "v4.0.0-rc.3");
    }

    function test_VerifierHash() public view {
        // The VERIFIER_HASH for v4.0.0-rc.3 Groth16 verifier
        bytes32 expectedHash = 0x11b6a09d63d255ad425ee3a7f6211d5ec63fbde9805b40551c3136275b6f4eb4;
        assertEq(verifier.VERIFIER_HASH(), expectedHash);
    }

    function test_ZkCreditProgramVKey() public view {
        // The verification key generated by SP1 for the zkCredit program
        bytes32 expectedVKey = 0x00d8368ebc6b3182ab36aa155e295897798a2b997db6c3bcb12a8387b571c476;
        assertEq(verifier.ZKCREDIT_PROGRAM_VKEY(), expectedVKey);
    }

    function test_HashPublicValues() public view {
        // Test public values hashing
        bytes memory publicValues = abi.encodePacked(
            bytes32(0x0000000000000000010000000000000000000000000000000000000000000000),
            bytes32(0x0100000000000000030000000000000002000000000000000200000000000000)
        );
        bytes32 hash = verifier.hashPublicValues(publicValues);
        // Hash should be non-zero and within BN254 field
        assertTrue(hash != bytes32(0));
        assertTrue(uint256(hash) < (1 << 253));
    }
}
